file=open("Shivam.txt","r")
print(file.read())
file.close()
file=open("Shivam.txt","w")
file.write("Hello everyone")
file.close()
file=open("Shivam.txt","a")
file.write("My name is Shivam")
file.close()